### ISSUE TITLE
layout mode and more

### ISSUE THREAD

**Issue by stoneboot593418** [EclipseMenu/EclipseMenu#109] opened 2024-12-03 14:22 UTC
### What feature would you like to see?

please add layout mode, a clickbot to the macro and rgb icons with options for player color 1 and 2, glow and wave trail

**Comment by FireMario211** [comment] 2024-12-03 15:15
Duplicate of https://github.com/EclipseMenu/EclipseMenu/issues/59

**Closed by FireMario211** 2024-12-03 15:15 UTC
